extends: default

ignore:
  - node_modules/
  - pnpm-lock.yaml

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  document-start: disable
  truthy:
    level: warning
    check-keys: false
  comments:
    min-spaces-from-content: 1
