catalog:
  '@biomejs/biome': 2.3.10
  '@commitlint/cli': 20.2.0
  '@commitlint/config-conventional': 20.2.0
  '@fast-check/vitest': 0.2.4
  '@secretlint/secretlint-rule-preset-recommend': 11.2.5
  '@stryker-mutator/core': 9.4.0
  '@stryker-mutator/typescript-checker': 9.4.0
  '@stryker-mutator/vitest-runner': 9.4.0
  '@types/node': 25.0.3
  '@vitest/coverage-v8': 4.0.16
  commander: 14.0.2
  dependency-cruiser: 17.3.5
  fast-check: 4.5.3
  lefthook: 2.0.13
  remark: 15.0.1
  remark-cli: 12.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-lint: 10.0.1
  remark-preset-lint-consistent: 6.0.1
  remark-preset-lint-recommended: 7.0.1
  remark-toc: 9.0.0
  secretlint: 11.2.5
  sharp: 0.34.5
  ts-node: 10.9.2
  typedoc: 0.28.15
  typedoc-plugin-merge-modules: 7.0.0
  typedoc-theme-hierarchy: 6.0.0
  typescript: 5.9.3
  vitest: 4.0.16

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
